### ISSUE TITLE
Triage issues for v0.4.0

### ISSUE THREAD

**Issue by mikeboers** [mikeboers/PyAV#268]
There has been a ton of work done since v0.3.3. We should cut out a new release.

However, I get the feeling that there are some regressions with it. We should triage the tickets still open since v0.3.3 to make sure they can be "ignored" for a new release.

*(edited to just be the issues left to address)*

- [ ] Assert no blocking issues on GitHub:
  - [ ] #202 
  - [ ] #212
  - [ ] #257 
- [ ] Document everything backwards incompatible in changelog:
  - [ ] ``Stream.encode`` returns a list of packets, instead of a single packet.
  - [ ] ``AudioFifo`` and ``AudioResampler`` will raise ``ValueError`` if input frames
  inconsistant ``pts``.
  - [ ] ``CodecContext.rate`` has been removed, but proxied to ``VideoCodecContext.framerate``
  and ``AudioCodecContext.sample_rate``. The definition is effectively inverted from
  the old one (i.e. for 24fps it used to be ``1/24`` and is now ``24/1``).
  - [ ] Fractions (e.g. ``time_base``, ``rate``) will be ``None`` if they are invalid.
  - [ ] ``InputContainer.seek`` and ``Stream.seek`` will raise TypeError if given
  a float, when previously they converted it from seconds.

😨

**Comment by mikeboers** [comment]
I'm tempted to just cut a `v0.4.0` right now. The tests pass as is. That is what they are there for. If there is something showstopping surely someone would have either said by now, or it should be trivial to fix in a `v0.4.1`.

**Comment by Schamper** [comment]
Any update on this?

**Comment by mikeboers** [comment]
No not really.

I've had a lot of personal stuff coming up. Honestly, while I've been reading all of the notifications from GitHub (as you can tell my be noticing this at all) I've been stuffing them into a "FLOSS" folder for when I eventually dig myself out.

As responsible as it may or may not be, I think I could be okay with releasing as-is, and seeing what happens. Can I get some 👍 on that?

**Comment by Schamper** [comment]
👍 from me

**Comment by tuxuser** [comment]
I would appreciate that too!

**Comment by notedit** [comment]
+1

**Comment by mikeboers** [comment]
So... uh... I did this.

A couple tests fail, I think because of FFmpeg changes in the ~6 months since I've run them.
